/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Models.Categoria;
import Models.Marca;
import Models.Peticiones;
import Models.Sucursal;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author XD
 */
public class VistaMarcaSucursalCate extends javax.swing.JFrame {

    /**
     * Creates new form vistaProductos
     */
    private String idGlobalMarca= null;
    private String idGlobalCategoria= null;
    private String idGlobalSucursal = null;
    
    public VistaMarcaSucursalCate() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelCodigoPostal = new javax.swing.JLabel();
        labelDireccionSucursal = new javax.swing.JLabel();
        labelNombreMarca = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtBusquedaCategoria = new javax.swing.JTextField();
        txtNombreCategoria = new javax.swing.JTextField();
        txtCodPostalSuc = new javax.swing.JTextField();
        txtCorreoSucursal = new javax.swing.JTextField();
        labelBusquedaCategoria = new javax.swing.JLabel();
        labelCorreoSucursal = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnEliminarCategoria = new javax.swing.JButton();
        btnAgregarCategoria = new javax.swing.JButton();
        btnEditarCategoria = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtBuscarMarca = new javax.swing.JTextField();
        txtNombremMarca = new javax.swing.JTextField();
        labelBusquedaMarca = new javax.swing.JLabel();
        labelNombreCategoria = new javax.swing.JLabel();
        btnEditarMarca = new javax.swing.JButton();
        btnEliminarMarca = new javax.swing.JButton();
        btnBuscarMarca = new javax.swing.JButton();
        labelNombreSucursal = new javax.swing.JLabel();
        txtNombreSucursal = new javax.swing.JTextField();
        txtDireccionSucursal = new javax.swing.JTextField();
        labelTelefonoSucursal = new javax.swing.JLabel();
        txtTelefonoSucursal = new javax.swing.JTextField();
        btnEditarSucursal = new javax.swing.JButton();
        btnEliminarSucursal = new javax.swing.JButton();
        btnAgregarSucursal = new javax.swing.JButton();
        txtBusquedaSucursal = new javax.swing.JTextField();
        labelBusquedaSucursal = new javax.swing.JLabel();
        txtImagenMarca = new javax.swing.JTextField();
        labelImagenMarca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(33, 45, 62));
        jPanel2.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("X");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel14);
        jLabel14.setBounds(850, 0, 30, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("_");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2);
        jLabel2.setBounds(810, 0, 30, 30);

        jLabel3.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agregar MSC");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(400, 10, 90, 20);

        jLabel4.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LaParis");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 10, 60, 20);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        jPanel3.setBackground(new java.awt.Color(245, 238, 210));
        jPanel3.setLayout(null);

        labelCodigoPostal.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        labelCodigoPostal.setForeground(new java.awt.Color(117, 107, 65));
        labelCodigoPostal.setText("C.P");
        jPanel3.add(labelCodigoPostal);
        labelCodigoPostal.setBounds(380, 360, 60, 30);

        labelDireccionSucursal.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        labelDireccionSucursal.setForeground(new java.awt.Color(117, 107, 65));
        labelDireccionSucursal.setText("Dirección");
        jPanel3.add(labelDireccionSucursal);
        labelDireccionSucursal.setBounds(90, 360, 90, 30);

        labelNombreMarca.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        labelNombreMarca.setForeground(new java.awt.Color(117, 107, 65));
        labelNombreMarca.setText("Nombre de la Marca");
        jPanel3.add(labelNombreMarca);
        labelNombreMarca.setBounds(90, 100, 170, 30);

        jLabel10.setFont(new java.awt.Font("Gotham Thin", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(117, 107, 65));
        jLabel10.setText("> DATOS DE MARCA ");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(90, 20, 260, 30);

        txtBusquedaCategoria.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        txtBusquedaCategoria.setText("BUSCAR CATEGORÍA...");
        txtBusquedaCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 45, 62)));
        txtBusquedaCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBusquedaCategoriaMouseClicked(evt);
            }
        });
        jPanel3.add(txtBusquedaCategoria);
        txtBusquedaCategoria.setBounds(490, 60, 210, 30);

        txtNombreCategoria.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jPanel3.add(txtNombreCategoria);
        txtNombreCategoria.setBounds(490, 130, 190, 30);

        txtCodPostalSuc.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        txtCodPostalSuc.setText("85490");
        txtCodPostalSuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodPostalSucActionPerformed(evt);
            }
        });
        jPanel3.add(txtCodPostalSuc);
        txtCodPostalSuc.setBounds(380, 390, 80, 30);

        txtCorreoSucursal.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        txtCorreoSucursal.setText("laparis@yahoo.com");
        jPanel3.add(txtCorreoSucursal);
        txtCorreoSucursal.setBounds(490, 390, 190, 30);

        labelBusquedaCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBusquedaCategoria.setText("Q");
        labelBusquedaCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 45, 62)));
        labelBusquedaCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBusquedaCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBusquedaCategoriaMouseClicked(evt);
            }
        });
        jPanel3.add(labelBusquedaCategoria);
        labelBusquedaCategoria.setBounds(700, 60, 30, 30);

        labelCorreoSucursal.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        labelCorreoSucursal.setForeground(new java.awt.Color(117, 107, 65));
        labelCorreoSucursal.setText("Correo");
        jPanel3.add(labelCorreoSucursal);
        labelCorreoSucursal.setBounds(490, 360, 120, 30);

        jLabel13.setFont(new java.awt.Font("Gotham Thin", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(117, 107, 65));
        jLabel13.setText("< Regresar ");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel13);
        jLabel13.setBounds(0, 0, 90, 50);

        btnEliminarCategoria.setText("Eliminar");
        btnEliminarCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCategoriaActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminarCategoria);
        btnEliminarCategoria.setBounds(730, 150, 90, 30);

        btnAgregarCategoria.setText("Agregar");
        btnAgregarCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCategoriaActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregarCategoria);
        btnAgregarCategoria.setBounds(730, 190, 90, 30);

        btnEditarCategoria.setText("Editar");
        btnEditarCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCategoriaActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditarCategoria);
        btnEditarCategoria.setBounds(730, 110, 90, 30);

        jLabel15.setFont(new java.awt.Font("Gotham Thin", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(117, 107, 65));
        jLabel15.setText("> DATOS DE SUCURSAL ");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(90, 240, 260, 30);

        jLabel16.setFont(new java.awt.Font("Gotham Thin", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(117, 107, 65));
        jLabel16.setText("> DATOS DE CATEGORÍA ");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(490, 20, 260, 30);

        txtBuscarMarca.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        txtBuscarMarca.setText("BUSCAR MARCA...");
        txtBuscarMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 45, 62)));
        txtBuscarMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarMarcaMouseClicked(evt);
            }
        });
        jPanel3.add(txtBuscarMarca);
        txtBuscarMarca.setBounds(90, 60, 190, 30);

        txtNombremMarca.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jPanel3.add(txtNombremMarca);
        txtNombremMarca.setBounds(90, 130, 190, 30);

        labelBusquedaMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBusquedaMarca.setText("Q");
        labelBusquedaMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 45, 62)));
        labelBusquedaMarca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBusquedaMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBusquedaMarcaMouseClicked(evt);
            }
        });
        jPanel3.add(labelBusquedaMarca);
        labelBusquedaMarca.setBounds(280, 60, 30, 30);

        labelNombreCategoria.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        labelNombreCategoria.setForeground(new java.awt.Color(117, 107, 65));
        labelNombreCategoria.setText("Nombre de la Categoría");
        jPanel3.add(labelNombreCategoria);
        labelNombreCategoria.setBounds(490, 100, 170, 30);

        btnEditarMarca.setText("Editar");
        btnEditarMarca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMarcaActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditarMarca);
        btnEditarMarca.setBounds(310, 110, 90, 30);

        btnEliminarMarca.setText("Eliminar");
        btnEliminarMarca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMarcaActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminarMarca);
        btnEliminarMarca.setBounds(310, 150, 90, 30);

        btnBuscarMarca.setText("Agregar");
        btnBuscarMarca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMarcaActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscarMarca);
        btnBuscarMarca.setBounds(310, 190, 90, 30);

        labelNombreSucursal.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        labelNombreSucursal.setForeground(new java.awt.Color(117, 107, 65));
        labelNombreSucursal.setText("Nombre de la Sucursal");
        jPanel3.add(labelNombreSucursal);
        labelNombreSucursal.setBounds(90, 290, 170, 30);

        txtNombreSucursal.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        txtNombreSucursal.setText("La paris centro");
        jPanel3.add(txtNombreSucursal);
        txtNombreSucursal.setBounds(90, 320, 190, 30);

        txtDireccionSucursal.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        txtDireccionSucursal.setText("Av. Serdan local #5");
        txtDireccionSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionSucursalActionPerformed(evt);
            }
        });
        jPanel3.add(txtDireccionSucursal);
        txtDireccionSucursal.setBounds(90, 390, 270, 30);

        labelTelefonoSucursal.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        labelTelefonoSucursal.setForeground(new java.awt.Color(117, 107, 65));
        labelTelefonoSucursal.setText("Telefono");
        jPanel3.add(labelTelefonoSucursal);
        labelTelefonoSucursal.setBounds(310, 290, 70, 30);

        txtTelefonoSucursal.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        txtTelefonoSucursal.setText("622-123-45-32");
        txtTelefonoSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoSucursalActionPerformed(evt);
            }
        });
        jPanel3.add(txtTelefonoSucursal);
        txtTelefonoSucursal.setBounds(310, 320, 130, 30);

        btnEditarSucursal.setText("Editar");
        btnEditarSucursal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarSucursalActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditarSucursal);
        btnEditarSucursal.setBounds(740, 310, 90, 30);

        btnEliminarSucursal.setText("Eliminar");
        btnEliminarSucursal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSucursalActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminarSucursal);
        btnEliminarSucursal.setBounds(740, 350, 90, 30);

        btnAgregarSucursal.setText("Agregar");
        btnAgregarSucursal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSucursalActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregarSucursal);
        btnAgregarSucursal.setBounds(740, 390, 90, 30);

        txtBusquedaSucursal.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        txtBusquedaSucursal.setText("BUSCAR SUCURSAL...");
        txtBusquedaSucursal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 45, 62)));
        txtBusquedaSucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBusquedaSucursalMouseClicked(evt);
            }
        });
        jPanel3.add(txtBusquedaSucursal);
        txtBusquedaSucursal.setBounds(490, 270, 220, 30);

        labelBusquedaSucursal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBusquedaSucursal.setText("Q");
        labelBusquedaSucursal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 45, 62)));
        labelBusquedaSucursal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBusquedaSucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBusquedaSucursalMouseClicked(evt);
            }
        });
        jPanel3.add(labelBusquedaSucursal);
        labelBusquedaSucursal.setBounds(710, 270, 30, 30);

        txtImagenMarca.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        jPanel3.add(txtImagenMarca);
        txtImagenMarca.setBounds(90, 190, 190, 30);

        labelImagenMarca.setFont(new java.awt.Font("Gotham Thin", 0, 14)); // NOI18N
        labelImagenMarca.setForeground(new java.awt.Color(117, 107, 65));
        labelImagenMarca.setText("Imagen");
        jPanel3.add(labelImagenMarca);
        labelImagenMarca.setBounds(90, 160, 170, 30);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 900, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
       
        System.exit(0);        
        
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtCodPostalSucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodPostalSucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodPostalSucActionPerformed

    private void txtDireccionSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionSucursalActionPerformed

    private void txtTelefonoSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoSucursalActionPerformed

    private void txtBusquedaSucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBusquedaSucursalMouseClicked
        // TODO add your handling code here:
        
        txtBusquedaSucursal.setText("");
        //txtBusquedaSucursal.setFocusable(true);
    }//GEN-LAST:event_txtBusquedaSucursalMouseClicked

    private void btnBuscarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMarcaActionPerformed
       
       String nombre = txtNombremMarca.getText().trim();
       String imagen = txtImagenMarca.getText().trim();
        
        if(validarCampo(txtNombremMarca, labelNombreMarca)== true){
            if (validarCampo(txtImagenMarca, labelImagenMarca) == true) {
                Gson r = new GsonBuilder().create();
                Marca m = new Marca();
                m.setNombre(nombre);
                m.setImagen(imagen);
                String s = r.toJson(m);
                String uri = "http://lplaparis.azurewebsites.net/ServiceMarcas.svc/rest/agregar-marca";

                Peticiones p = new Peticiones();
                //p.post(uri, s);
                if (p.post(uri, s) != null) {
                    JOptionPane.showMessageDialog(null, "Agregado con exito");
                } else {
                    JOptionPane.showMessageDialog(null, "Ocurrio un problema intenta de nuevo");
                }
            }
        }
        
    }//GEN-LAST:event_btnBuscarMarcaActionPerformed

    private void btnAgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCategoriaActionPerformed
       
        String nombre = txtNombreCategoria.getText().trim();
        if (validarCampo(txtNombreCategoria, labelNombreCategoria) == true) {
            
            Gson r = new GsonBuilder().create();
            Categoria m = new Categoria();
            m.setNombre(nombre);
            String s = r.toJson(m);
            String uri = "http://lplaparis.azurewebsites.net/ServiceCategorias.svc/rest/agregar-categoria";

            Peticiones p = new Peticiones();
            //p.post(uri, s);
            if (p.post(uri, s) != null) {
                JOptionPane.showMessageDialog(null, "Agregado con exito");
                limpiarCamposCategoria();
            } else {
                JOptionPane.showMessageDialog(null, "Ocurrio un problema intenta de nuevo");
            }
        }
        
    }//GEN-LAST:event_btnAgregarCategoriaActionPerformed

    private void btnAgregarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSucursalActionPerformed
     
        String nombre = txtNombreSucursal.getText().trim();
        String direccion = txtDireccionSucursal.getText().trim();
        String telefono = txtTelefonoSucursal.getText().trim();
        int codpostal = Integer.parseInt(txtCodPostalSuc.getText().trim());
        String correo = txtCorreoSucursal.getText().trim();

        if (validarCampo(txtNombreSucursal, labelNombreSucursal) == true) {
            if (validarCampo(txtDireccionSucursal, labelDireccionSucursal) == true) {
                if (validarCampo(txtTelefonoSucursal, labelTelefonoSucursal) == true) {
                    if (validarCampo(txtCodPostalSuc, labelCodigoPostal) == true) {
                        if (validarCampo(txtCorreoSucursal, labelCorreoSucursal) == true) {
                            Gson r = new GsonBuilder().create();
                            Sucursal s = new Sucursal();
                            s.setNombre(nombre);
                            s.setDireccion(direccion);
                            s.setTelefono(telefono);
                            s.setCodPostal(codpostal);
                            s.setCorreo(correo);

                            String sc = r.toJson(s);
                            String uri = "http://lplaparis.azurewebsites.net/ServiceSucursal.svc/rest/agregar-sucursal";

                            Peticiones p = new Peticiones();
                           // p.post(uri, sc);
                            if (p.post(uri, sc) != null) {
                                JOptionPane.showMessageDialog(null, "Agregado con éxito");
                                limpiarCamposSucursal();
                            } else {
                                JOptionPane.showMessageDialog(null, "Ocurrio un problema intenta de nuevo");
                            }
                        }
                    }
                }
            }
        }
        
    }//GEN-LAST:event_btnAgregarSucursalActionPerformed
     
    private void btnEditarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMarcaActionPerformed
        String nombre = txtNombremMarca.getText().trim();
        String imagen = txtImagenMarca.getText().trim();
        
        if(validarCampo(txtNombremMarca, labelNombreMarca)== true){
            if (validarCampo(txtImagenMarca, labelImagenMarca) == true) {
                 int selec = JOptionPane.showOptionDialog(null, "¿Estas seguro de eliminar?", "ADVERTENCIA", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"SI", "NO"}, "SI");
                if (selec != -1) {
                    if ((selec + 1) == 1) {
                Gson r = new GsonBuilder().create();
                Marca m = new Marca();
                m.setId(Integer.parseInt(idGlobalMarca));
                m.setNombre(nombre);
                m.setImagen(imagen);
                String s = r.toJson(m);
                String uri = "http://lplaparis.azurewebsites.net/ServiceMarcas.svc/rest/editar-marca";

                Peticiones p = new Peticiones();
              
                if (p.put(uri, s) == true) {
                    JOptionPane.showMessageDialog(null, "Editado con éxito");
                    limpiarCamposMarcas();
                } else {
                    JOptionPane.showMessageDialog(null, "Ocurrio un problema intenta de nuevo");
                }
            }
        }        
            }
        }
    }//GEN-LAST:event_btnEditarMarcaActionPerformed
    
    void rellenarCamposBuscarMarca(String nombre){
        Peticiones p = new Peticiones();
        Gson r = new GsonBuilder().create();
        String uri = "http://lplaparis.azurewebsites.net/ServiceMarcas.svc/rest/buscar-marca";
        Marca ss = new Marca();
        ss.setNombre(nombre);        
         String sc = r.toJson(ss);
        
        String s = p.getByPost(uri,sc);
        if(s.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "No se encontro el parametro de busqueda");
        }else{
            Gson gs = new Gson();  
            Marca ma = gs.fromJson(s, Marca.class);
            idGlobalMarca= String.valueOf(ma.getId());
            txtNombremMarca.setText(ma.getNombre());
            txtImagenMarca.setText(ma.getImagen());
        }
                
    }
    
    void rellenarCamposBuscarCategoria(String nombre){
        Peticiones p = new Peticiones();
        Gson r = new GsonBuilder().create();
        String uri = "http://lplaparis.azurewebsites.net/ServiceCategorias.svc/rest/buscar-categoria";
        Categoria ss = new Categoria();
        ss.setNombre(nombre);
        
        String sc = r.toJson(ss);
        
        String s = p.getByPost(uri,sc);
        if(s.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "No se encontro el parametro de busqueda");
        }else{
            Gson gs = new Gson();  
            Categoria ma = gs.fromJson(s, Categoria.class);
            idGlobalCategoria = String.valueOf(ma.getId());
            txtNombreCategoria.setText(ma.getNombre());
        }
                
    }
    
    void rellenarCamposBuscarSucursal(String nombre){
        Peticiones p = new Peticiones();
        Gson r = new GsonBuilder().create();
        String uri = "http://lplaparis.azurewebsites.net/ServiceSucursal.svc/rest/buscar-sucursal";
        Sucursal ss = new Sucursal();
        ss.setNombre(nombre);
        
        String sc = r.toJson(ss);
        
        String s = p.getByPost(uri,sc);
        if(s.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "No se encontro el parametro de busqueda");
        }else{
            Gson gs = new Gson();  
            Sucursal ma = gs.fromJson(s, Sucursal.class);
            idGlobalSucursal = String.valueOf(ma.getId());
            txtNombreSucursal.setText(ma.getNombre());
            txtTelefonoSucursal.setText(ma.getTelefono());
            txtDireccionSucursal.setText(ma.getDireccion());
            txtCodPostalSuc.setText(String.valueOf(ma.getCodPostal()));
            txtCorreoSucursal.setText(ma.getCorreo());
        }
                
    }
      
    private void labelBusquedaMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBusquedaMarcaMouseClicked
        
        String busquedaMarca = txtBuscarMarca.getText().trim();
        if(validarCampo(txtBuscarMarca, labelBusquedaMarca)== true){
           rellenarCamposBuscarMarca(busquedaMarca);  
        }
       
        
        
    }//GEN-LAST:event_labelBusquedaMarcaMouseClicked

    private void btnEliminarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMarcaActionPerformed
       
     if (idGlobalMarca!=null) {          
        int selec = JOptionPane.showOptionDialog(null, "¿Estas seguro de eliminar?", "ADVERTENCIA",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"SI", "NO"}, "SI");
        if (selec != -1) {
            if ((selec + 1) == 1) {               
                            
                  String uri = "http://lplaparis.azurewebsites.net/ServiceMarcas.svc/rest/eliminar-marca/";

                Peticiones p = new Peticiones();
              
                if (p.delete(uri, idGlobalMarca) == true) {
                    JOptionPane.showMessageDialog(null, "Eliminado con éxito");
                    limpiarCamposMarcas();
                } else {
                    JOptionPane.showMessageDialog(null, "Ocurrio un problema intenta de nuevo");
                }
                }
            }
        }else{
         JOptionPane.showMessageDialog(null, "Debes tener un elemento definido para eliminarlo");
     }
     
    }//GEN-LAST:event_btnEliminarMarcaActionPerformed

    private void btnEliminarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCategoriaActionPerformed
        // TODO add your handling code here:
        if (idGlobalCategoria!=null) {          
        int selec = JOptionPane.showOptionDialog(null, "¿Estas seguro de eliminar?", "ADVERTENCIA",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"SI", "NO"}, "SI");
        if (selec != -1) {
            if ((selec + 1) == 1) {               
                            
                  String uri = "http://lplaparis.azurewebsites.net/ServiceCategorias.svc/rest/eliminar-categoria/";

                Peticiones p = new Peticiones();
                //p.post(uri, s);
                if (p.delete(uri, idGlobalCategoria) == true) {
                    JOptionPane.showMessageDialog(null, "Eliminado con éxito");
                    limpiarCamposCategoria();
                } else {
                    JOptionPane.showMessageDialog(null, "Ocurrio un problema intenta de nuevo");
                }
                }
            }
        }else{
         JOptionPane.showMessageDialog(null, "Debes tener un elemento definido para eliminarlo");
     }
        
    }//GEN-LAST:event_btnEliminarCategoriaActionPerformed

    private void labelBusquedaCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBusquedaCategoriaMouseClicked
        // TODO add your handling code here:
        String busquedaCategoria = txtBusquedaCategoria.getText().trim();
        if(validarCampo(txtBusquedaCategoria, labelBusquedaCategoria)== true){
           rellenarCamposBuscarCategoria(busquedaCategoria); 
        }        
    }//GEN-LAST:event_labelBusquedaCategoriaMouseClicked

    private void labelBusquedaSucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBusquedaSucursalMouseClicked
        
         String busquedaSucursal = txtBusquedaSucursal.getText().trim();
        if(validarCampo(txtBusquedaSucursal, labelBusquedaSucursal)== true){
            rellenarCamposBuscarSucursal(busquedaSucursal); 
        }
    }//GEN-LAST:event_labelBusquedaSucursalMouseClicked

    private void btnEditarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCategoriaActionPerformed
       
        String nombre =  txtNombreCategoria.getText().trim();
               
        if(validarCampo(txtNombreCategoria, labelNombreCategoria)== true){
             int selec = JOptionPane.showOptionDialog(null, "¿Estas seguro de eliminar?", "ADVERTENCIA",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"SI", "NO"}, "SI");
             if (selec != -1) {
            if ((selec + 1) == 1) { 
                Gson r = new GsonBuilder().create();
                Categoria m = new Categoria();
                m.setId(Integer.parseInt(idGlobalCategoria));
                m.setNombre(nombre);
                
                String s = r.toJson(m);
                String uri = "http://lplaparis.azurewebsites.net/ServiceCategorias.svc/rest/editar-categoria";

                Peticiones p = new Peticiones();
              
                if (p.put(uri, s) == true) {
                    JOptionPane.showMessageDialog(null, "Editado con éxito");
                    limpiarCamposCategoria();
                } else {
                    JOptionPane.showMessageDialog(null, "Ocurrio un problema intenta de nuevo");
                }
            }
         }
        }
    }//GEN-LAST:event_btnEditarCategoriaActionPerformed

    private void btnEditarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarSucursalActionPerformed
       
      String nombre =  txtNombreSucursal.getText().trim();
      String telefono = txtTelefonoSucursal.getText().trim();
      String direccion = txtDireccionSucursal.getText().trim();
      int codPost = Integer.parseInt(txtCodPostalSuc.getText().trim());
      String correo=txtCorreoSucursal.getText().trim();
                
              if (validarCampo(txtNombreSucursal, labelNombreSucursal) == true) {
            if (validarCampo(txtTelefonoSucursal, labelTelefonoSucursal) == true) {
                if (validarCampo(txtDireccionSucursal, labelDireccionSucursal) == true) {
                    if (validarCampo(txtCodPostalSuc, labelCodigoPostal) == true) {
                        if (validarCampo(txtCorreoSucursal, labelCorreoSucursal) == true) {

                            int selec = JOptionPane.showOptionDialog(null, "¿Estas seguro de eliminar?", "ADVERTENCIA", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"SI", "NO"}, "SI");
                            if (selec != -1) {
                                if ((selec + 1) == 1) {
                                    Gson r = new GsonBuilder().create();
                                    Sucursal m = new Sucursal();
                                    m.setId(Integer.parseInt(idGlobalSucursal));
                                    m.setNombre(nombre);
                                    m.setTelefono(telefono);
                                    m.setDireccion(direccion);
                                    m.setCodPostal(codPost);
                                    m.setCorreo(correo);
                                    

                                    String s = r.toJson(m);
                                    String uri = "http://lplaparis.azurewebsites.net/ServiceSucursal.svc/rest/editar-sucursal";

                                    Peticiones p = new Peticiones();

                                    if (p.put(uri, s) == true) {
                                        JOptionPane.showMessageDialog(null, "Editado con éxito");
                                        limpiarCamposSucursal();
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Ocurrio un problema intenta de nuevo");
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        
        
    }//GEN-LAST:event_btnEditarSucursalActionPerformed

    private void btnEliminarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSucursalActionPerformed
      
     if (idGlobalSucursal!=null) {          
        int selec = JOptionPane.showOptionDialog(null, "¿Estas seguro de eliminar?", "ADVERTENCIA",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"SI", "NO"}, "SI");
        if (selec != -1) {
            if ((selec + 1) == 1) {               
                            
                  String uri = "http://lplaparis.azurewebsites.net/ServiceSucursal.svc/rest/eliminar-sucursal/";

                Peticiones p = new Peticiones();
                //p.post(uri, s);
                if (p.delete(uri, idGlobalSucursal) == true) {
                    JOptionPane.showMessageDialog(null, "Eliminado con éxito");
                    limpiarCamposSucursal();
                } else {
                    JOptionPane.showMessageDialog(null, "Ocurrio un problema intenta de nuevo");
                }
                }
            }
        }else{
         JOptionPane.showMessageDialog(null, "Debes tener un elemento definido para eliminarlo");
     }     
        
    }//GEN-LAST:event_btnEliminarSucursalActionPerformed

    private void txtBusquedaCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBusquedaCategoriaMouseClicked
        // TODO add your handling code here:
        txtBusquedaCategoria.setText("");
    }//GEN-LAST:event_txtBusquedaCategoriaMouseClicked

    private void txtBuscarMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMarcaMouseClicked
        // TODO add your handling code here:
        txtBuscarMarca.setText("");
        
    }//GEN-LAST:event_txtBuscarMarcaMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        VistaProductos vp = new VistaProductos();
        vp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel13MouseClicked

    public Boolean validarCampo(JTextField campo, JLabel label){
       Boolean bandera = false;
        if(campo.getText().isEmpty()){
           JOptionPane.showMessageDialog(null,"El campo '"+label.getText()+"' es requerido");           
        }else{
            bandera = true;
        }
        return bandera ;
    }
    
    
    public void limpiarCamposSucursal(){
            idGlobalSucursal = null;
            txtNombreSucursal.setText("");
            txtTelefonoSucursal.setText("");
            txtDireccionSucursal.setText("");
            txtCodPostalSuc.setText("");
            txtCorreoSucursal.setText("");
    }
    
    public void limpiarCamposMarcas(){
        idGlobalMarca = null;
        txtNombremMarca.setText("");
        txtImagenMarca.setText("");
    }
    
    public void limpiarCamposCategoria(){
        idGlobalCategoria = null;
        txtNombreCategoria.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMarcaSucursalCate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMarcaSucursalCate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMarcaSucursalCate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMarcaSucursalCate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMarcaSucursalCate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCategoria;
    private javax.swing.JButton btnAgregarSucursal;
    private javax.swing.JButton btnBuscarMarca;
    private javax.swing.JButton btnEditarCategoria;
    private javax.swing.JButton btnEditarMarca;
    private javax.swing.JButton btnEditarSucursal;
    private javax.swing.JButton btnEliminarCategoria;
    private javax.swing.JButton btnEliminarMarca;
    private javax.swing.JButton btnEliminarSucursal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelBusquedaCategoria;
    private javax.swing.JLabel labelBusquedaMarca;
    private javax.swing.JLabel labelBusquedaSucursal;
    private javax.swing.JLabel labelCodigoPostal;
    private javax.swing.JLabel labelCorreoSucursal;
    private javax.swing.JLabel labelDireccionSucursal;
    private javax.swing.JLabel labelImagenMarca;
    private javax.swing.JLabel labelNombreCategoria;
    private javax.swing.JLabel labelNombreMarca;
    private javax.swing.JLabel labelNombreSucursal;
    private javax.swing.JLabel labelTelefonoSucursal;
    private javax.swing.JTextField txtBuscarMarca;
    private javax.swing.JTextField txtBusquedaCategoria;
    private javax.swing.JTextField txtBusquedaSucursal;
    private javax.swing.JTextField txtCodPostalSuc;
    private javax.swing.JTextField txtCorreoSucursal;
    private javax.swing.JTextField txtDireccionSucursal;
    private javax.swing.JTextField txtImagenMarca;
    private javax.swing.JTextField txtNombreCategoria;
    private javax.swing.JTextField txtNombreSucursal;
    private javax.swing.JTextField txtNombremMarca;
    private javax.swing.JTextField txtTelefonoSucursal;
    // End of variables declaration//GEN-END:variables
}
